### ISSUE TITLE
Hostile Combatants not showing

### ISSUE THREAD

**Issue by headcrabed13** [etriebe/combat-estimate#12]
Foundry VTT | Created Combat with id [kpmjU1wrl0rvrD9v]
backend.mjs:306 Foundry VTT | Created Combatant with id [WHM2HOERdzJpfbtk] in parent Combat [kpmjU1wrl0rvrD9v]
backend.mjs:306 Foundry VTT | Created ChatMessage with id [SM6mmfTyT4Btjwim]
backend.mjs:306 Foundry VTT | Created Combatant with id [kR52LnhFXrLCGEyl] in parent Combat [kpmjU1wrl0rvrD9v]
backend.mjs:306 Foundry VTT | Created ChatMessage with id [yNlNMFDaCMaKjeiE]
backend.mjs:306 Foundry VTT | Created Combatant with id [8YE0hEtw1tcI92zP] in parent Combat [kpmjU1wrl0rvrD9v]
backend.mjs:306 Foundry VTT | Created ChatMessage with id [IuOUnF2SsVjRUkox]
backend.mjs:306 Foundry VTT | Created Combatant with id [t0wG3YVP8fi8v8gZ] in parent Combat [kpmjU1wrl0rvrD9v]
backend.mjs:306 Foundry VTT | Created ChatMessage with id [xNtnlUxlVQLkgAKx]
backend.mjs:306 Foundry VTT | Created Combatant with id [WFDRwZsaYGg39nHc] in parent Combat [kpmjU1wrl0rvrD9v]
backend.mjs:306 Foundry VTT | Created ChatMessage with id [GER4EwKh11MyfZae]
backend.mjs:306 Foundry VTT | Created Combatant with id [pUfqRvKgf4mHuk10] in parent Combat [kpmjU1wrl0rvrD9v]
backend.mjs:306 Foundry VTT | Created ChatMessage with id [L4P8npjktOdYH09a]
backend.mjs:306 Foundry VTT | Created Combatant with id [unLSvvvgsDq5eY3H] in parent Combat [kpmjU1wrl0rvrD9v]
backend.mjs:306 Foundry VTT | Created ChatMessage with id [DDN7TWiQC9axbIfD]
foundry.js:3053 Foundry VTT | Rendering CombatEstimateDialog
dialog.js:71 Combatant Tarhun is friendly
ActorUtils.js:584 Unable to parse attack Fire Breath Weapon: SyntaxError: Invalid or unexpected token
getBestSingleAttack @ ActorUtils.js:584
getCombatDataPerRound @ ActorUtils.js:241
PCActor5e @ PCActor5e.js:12
getPCActorObject @ ActorUtils.js:62
populateCombatants @ dialog.js:72
activateListeners @ dialog.js:37
_render @ foundry.js:3090
async function (async)
_render @ foundry.js:3062
_render @ foundry.js:3764
render @ foundry.js:3021
(anonymous) @ module.js:32
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
dialog.js:71 Combatant Barrington is friendly
dialog.js:71 Combatant Sir Snuggles is friendly
dialog.js:71 Combatant Bruss is friendly
ActorUtils.js:234 Attempted to guess attack for Bruss the Oriented: 3 Handaxe attacks.
dialog.js:71 Combatant Jis Pin is friendly
ActorUtils.js:234 Attempted to guess attack for Jis Pin: 2 Elven Burst-Bow attacks.
dialog.js:71 Combatant Landuin is friendly
ActorUtils.js:234 Attempted to guess attack for Landuin Lor'lin: 1 Scrumptious (Rapier) attacks.
dialog.js:79 Combatant Adult Sea Dragon is hostile
ActorUtils.js:926 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'match')
[Detected 1 package: combat-estimate]
    at Function.getDamageWithResistance (ActorUtils.js:926)
    at Function.getInfoForAttackObject (ActorUtils.js:1062)
    at CombatEstimateDialog.getActorCombatSummary (dialog.js:154)
    at CombatEstimateDialog.populateCombatants (dialog.js:108)
    at CombatEstimateDialog.activateListeners (dialog.js:37)
    at CombatEstimateDialog._render (foundry.js:3090)
    at async CombatEstimateDialog._render (foundry.js:3764)
![MissingEnemies](https://user-images.githubusercontent.com/106010220/169685762-183cca7e-0943-43a2-b2d5-7d2011e25a7a.png)

**Comment by etriebe** [comment]
@headcrabed13 could you export the actor's json file and attach here for those with errors? That or you can DM me on discord and give me GM access to your world and I'll take a look there. Knowing what the syntax of the breath weapon is will help me figure out how to parse correctly. 😃 

ActorUtils.js:584 Unable to parse attack Fire Breath Weapon: SyntaxError: Invalid or unexpected token

Thanks for the report!

**Comment by headcrabed13** [comment]
Looking into "ActorUtils.js:584 Unable to parse attack Fire Breath Weapon: SyntaxError: Invalid or unexpected token" specifically,
I found that it was my Drakewarden Ranger's companion that I had put together (the fire breath it had apparently) that was causing the error.
Keeping it off the initiative tracker seems to have fixed the issue.

Thanks for the help!

**Comment by etriebe** [comment]
I can look into why companions aren't working if you want! Just let me know!

--Eric Triebe

________________________________
