### ISSUE TITLE
Blank Estimate with legendary creature

### ISSUE THREAD

**Issue by KonteiKeisei** [etriebe/combat-estimate#19]
Works as long as creature does not have legendary.
Legendary Able Monsters generate attached error.

Monsters imported with MrPrimatesDDB Importer
![image](https://user-images.githubusercontent.com/49371326/211393632-482f5e57-7fa3-49d1-8616-ea53e381ceb3.png)

Foundry V10 latest

**Comment by etriebe** [comment]
Which legendary monster?

**Comment by KonteiKeisei** [comment]
Seems to be all of them? I can do some testing?
I also have a dev pal of mine I can throw it by, if we find a solution ill post it. Probably user error. Usually is ;)

**Comment by etriebe** [comment]
Nope! I found a repro. Should have a fix tonight.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by etriebe** [comment]
Fixed in 1.0.24
