### ISSUE TITLE
Cannot Read Properties (SAVE)

### ISSUE THREAD

**Issue by KonteiKeisei** [etriebe/combat-estimate#21]
Getting the following error on a specific PC and legendary creature.
![image](https://user-images.githubusercontent.com/49371326/211557790-238ce580-c634-4cba-9c5f-d882361f5e81.png)

Can provide PC Json at request

Foundry V10 latest
System DND5e Latest

**Comment by etriebe** [comment]
Fixed in 1.0.25.
