### ISSUE TITLE
NaN Values

### ISSUE THREAD

**Issue by KonteiKeisei** [etriebe/combat-estimate#23]
After latest fix, getting NaN numbers in CE which causes failure in rounds to down calculation. For both NPC and PC.

![image](https://user-images.githubusercontent.com/49371326/211865055-cb9a00b9-eaf9-4544-bdd6-fab242a501ab.png)

Also might I add that you are awesome for how quick you look into these!

**Comment by etriebe** [comment]
Looking. Happy to help!

Which creature was this with the destructive wave?

**Comment by KonteiKeisei** [comment]
Values are missing now, which i suppose makes sense:

![image](https://user-images.githubusercontent.com/49371326/211891942-8f1939c7-6c8f-461a-856e-d097ddc2480d.png)

missing combatants are based on the Death Knight, but i modified them all really.

**Comment by KonteiKeisei** [comment]
![image](https://user-images.githubusercontent.com/49371326/211892761-a325b4a3-e9c9-459a-8c22-235451083a9c.png)

**Comment by KonteiKeisei** [comment]
Here is a player feature that is being filtered out:
![image](https://user-images.githubusercontent.com/49371326/211893785-238873aa-d642-408b-81dd-a73cf86e04a7.png)

**Comment by etriebe** [comment]
Ah, bummer. I'll take a look. I know Polearm Master won't be supported until I do some more work but regular attacks should be working.

**Comment by KonteiKeisei** [comment]
Looks like mostly spells are impacted for the NPC's Disintegrate and such. Good luck and again thanks for your work!
