### ISSUE TITLE
Attack action

### ISSUE THREAD

**Issue by thetipster** [etriebe/combat-estimate#7]
Level 15 fighter shows x2 attacks in calc, should be x3.

**Comment by etriebe** [comment]
Can you attach me the actor or send me a dnd beyond link? I can create a level 15 fighter but want to make sure it isn't something else.

--Eric Triebe

________________________________
From: thetipster ***@***.***>
Sent: Saturday, May 7, 2022 9:20:09 PM
To: etriebe/combat-estimate ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [etriebe/combat-estimate] Attack action (Issue #7)


Level 15 fighter shows x2 attacks in calc, should be x3.

**Comment by etriebe** [comment]
Just repro'd myself and I think it has to do with the character having 3 different extra attack features. I'm talking with Mr Primate about this but also working on a possible mitigation.

![image](https://user-images.githubusercontent.com/7503160/167313033-1df30dba-b519-4469-a285-2055a881c8de.png)

**Comment by etriebe** [comment]
Resolved with 1.0.10. 

https://github.com/etriebe/combat-estimate/releases/tag/1.0.10
